PisCRM/Models/Employees/EditViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PisCRM.Models.Employees
{
    public class EditViewModel
    {
        [System.Web.Mvc.HiddenInput]
        public int Id { get; set; }

        //[Required(ErrorMessage = "Внесете Email адреса.")]
        //[EmailAddress(ErrorMessage = "Внесете валидна Email адреса.")]
        //[Display(Name = "Email")]
        //public string Email { get; set; }

        [Required(ErrorMessage = "Внесете Име.")]
        [StringLength(100, ErrorMessage = "Max. 100 карактери.")]
        [Display(Name = "Име")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Внесете Презиме.")]
        [StringLength(100, ErrorMessage = "Max. 100 карактери.")]
        [Display(Name = "Презиме")]
        public string LastName { get; set; }

        [StringLength(100, ErrorMessage = "Max. 100 карактери.")]
        [Display(Name = "Работна позиција")]
        public string WorkPosition { get; set; }

        [Required(ErrorMessage = "Селектирајтe Роља")]
        [Display(Name = "Селектирајтe Роља")]
        public int RoleId { get; set; }

        [Display(Name = "Профилна слика")]
        public string ProfilePictureUrl { get; set; }
    }
}

PisCRM/Controllers/EmployeesController.cs
using PisCRM.FIlters;
using PisCRM.Framework;
using PisCRM.Infrastructure;
using PisCRM.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using PisCRM.Infrastructure.Alerts;
using PisCRM.Models.Employees;
using Domain.Managers;
using PisCRM.Contracts;
using PisCRM.Contracts.Enums;
using Framework;
using System.Security.Principal;
using Omu.ValueInjecter;

namespace PisCRM.Controllers
{
    [Authorize]
    public class EmployeesController : BaseController
    {
        private readonly ApplicationUserManager _userManager;
        private readonly EmployeeManager _employeeManager;
        private readonly RoleManager _roleManager;
        private readonly IIdentity _identity;

        public EmployeesController(ICurrentUser currentUser, ApplicationUserManager userManager,
            EmployeeManager employeeManager, RoleManager roleManager, IIdentity identity)
            : base(currentUser)
        {
            _userManager = userManager;
            _employeeManager = employeeManager;
            _roleManager = roleManager;
            _identity = identity;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult IndexPaging(int page = 1, string searchWord = "")
        {
            var model = new PagedData<ApplicationUser>();
            IQueryable<ApplicationUser> users = _employeeManager.GetEmployees(searchWord);
            model.Data = model.PreparePage(users);

            return View(model);
        }

        [AdminRoleFilter]
        public ActionResult Create()
        {
            var model = new RegisterViewModel();
            model.RoleId = (int)Roles.Admin;

            return View(model);
        }

        [AdminRoleFilter]
        [HttpPost]
        public ActionResult Create(RegisterViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var user = new ApplicationUser { UserName = model.Email, DateCreated = DateTime.UtcNow };
            user.InjectFrom(model);

            var result = _userManager.Create(user, model.Password);

            if (!result.Succeeded)
            {
                ModelState.AddModelError("CreateUserErrorResponse", result.Errors.First());
                return View(model);
            }
            else
            {
                var role = Enum.GetName(typeof(Roles), model.RoleId);

                if (role == null)
                {
                    AddErrors(result);
                    ModelState.AddModelError("CreateUserErrorResponse", result.Errors.First());
                    return View(model);
                }
                else
                {
                    var roleResult = _userManager.AddToRole(user.Id, ((Roles)model.RoleId).GetDescription());

                    if (!roleResult.Succeeded)
                    {
                        AddErrors(roleResult);
                        ModelState.AddModelError("CreateUserErrorResponse", roleResult.Errors.First());
                        return View(model);
                    }
                }

                if (Request.Files.Count == 1)
                    _employeeManager.SaveProfilePhoto(user.Id, Request.Files[0]);
            }

            return RedirectToAction<EmployeesController>(c => c.Index())
                .WithSuccess("Вработениот е успешно креиран!");
        }

        public ActionResult Details(int id)
        {
            var model = _employeeManager.GetSingle(id);

            if (model == null)
            {
                return RedirectToAction<EmployeesController>(c => c.Index())
                    .WithError("Не постои таков вработен.");
            }

            return View(model);
        }

        [AdminRoleFilter]
        public ActionResult Edit(int id)
        {
            var user = _employeeManager.GetSingle(id);

            if (user == null)
            {
                return RedirectToAction<EmployeesController>(c => c.Index())
                    .WithError("Не е пронајден вработениот! Обидете се повторно.");
            }

            var model = new EditViewModel();
            model.InjectFrom(user);

            if (user.Role != null)
                model.RoleId = user.Role.RoleId;

            return View(model);
        }

        [AdminRoleFilter]
        [HttpPost]
        public ActionResult Edit(EditViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var user = _employeeManager.GetSingle(model.Id);

            if (user == null)
            {
                return RedirectToAction<EmployeesController>(c => c.Index())
                    .WithError("Не е пронајден вработениот! Обидете се повторно.");
            }

            user.FirstName = model.FirstName;
            user.LastName = model.LastName;
            user.WorkPosition = model.WorkPosition;

            var roleResult = _employeeManager.SaveEmployeeRole(model.Id, model.RoleId);

            if (!roleResult)
                return RedirectToAction<EmployeesController>(c => c.Index()).WithError("Настана грешка. Ве молиме обидете се повторно.");

            if (Request.Files.Count == 1)
                _employeeManager.SaveProfilePhoto(user.Id, Request.Files[0]);

            _employeeManager.Update(user);

            return RedirectToAction<EmployeesController>(c => c.Index())
                .WithSuccess("Информациите за вработениот се успешно зачувани!");
        }

        [AdminRoleFilter]
        public ActionResult Delete(int id)
        {
            var model = _employeeManager.GetSingle(id);

            if (model == null)
                return RedirectToAction<EmployeesController>(c => c.Index())
                    .WithError("Не е пронајден вработениот! Обидете се повторно.");

            return View(model);
        }

        [AdminRoleFilter]
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            var user = _employeeManager.GetSingle(id);

            if (user == null)
                return RedirectToAction<EmployeesController>(c => c.Index())
                    .WithError("Не е пронајден вработениот! Обидете се повторно.");

            if (user.Id == _identity.GetUserId<int>())
                return RedirectToAction<EmployeesController>(c => c.Index())
                    .WithError("Не можете да ја избришете сопствената корисничка сметка!");

            _employeeManager.Delete(user.Id);

            return RedirectToAction<EmployeesController>(c => c.Index())
                .WithSuccess("Вработениот е успешно избришан!");
        }

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }
    }
}

PisCRM/Views/Employees/Create.cshtml
@model PisCRM.Models.RegisterViewModel
@{
    ViewBag.Title = "Креирај вработен";
    ViewBag.TitleDescription = "Креирај нов вработен";
}

<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">

            @using (Html.BeginForm("Create", "Employees", FormMethod.Post, new { role = "form", enctype = "multipart/form-data" }))
            {
                <div class="box-body">
                    @Html.AntiForgeryToken()

                    @Html.CustomValidationMessage("CreateUserErrorResponse")

                    @Html.EditorForModel()

                    <div class="form-group" data-property-name="file">
                        <label class="" for="file">Профилна слика</label>
                        <input class="upload" type="file" id="file" accept="image/*" name="file" onchange="fileSelected('image', 'file')" />
                    </div>

                    <div class="box-footer">
                        <input type="submit" value="Креирај вработен" class="btn btn-primary" />
                    </div>
                </div>
            }
        </div>
    </div>
</div>



PisCRM/Views/Employees/Delete.cshtml
@model ApplicationUser
@{
    ViewBag.Title = "Избриши вработен";
    ViewBag.TitleDescription = "";
}

<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">

            @using (Html.BeginForm("Delete", "Employees", FormMethod.Post, new { role = "form" }))
            {
                <div class="box-body">
                    @Html.AntiForgeryToken()

                    @Html.HiddenFor(model => model.Id)
                    <p>
                        Дали сте сигурни дека сакате да го избришете вработениот: <b>@Model.FullName </b>
                        со Email адреса: <b>@Model.Email</b>?
                    </p>
                    <p>Акцијата е неповратна!</p>

                    <div class="box-footer">
                        <input type="submit" value="Избриши вработен" class="btn btn-danger" />
                    </div>
                </div>
            }
        </div>
    </div>
</div>

PisCRM/Views/Employees/Details.cshtml
@model PisCRM.Contracts.ApplicationUser

@using Roles = PisCRM.Contracts.Enums.Roles;

@{ ViewBag.Title = "Профил - " + Model.FullName;
 ViewBag.TitleDescription = "";
}

<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">

            <div class="box-body">
                <div class="form-group">
                    <label>Име и презиме: </label>@Model.FullName
                </div>

                <div class="form-group">
                    <label>Email адреса: </label>@Model.Email
                </div>

                <div class="form-group">
                    <label>Работна позиција: </label>@(!string.IsNullOrEmpty(Model.WorkPosition) ? Model.WorkPosition : "/")
                </div>

                @if (SiteSession.CurrentUser != null
                                    && SiteSession.CurrentUser.Role.RoleId == (int)Roles.Admin)
                {
                    var roleEnum = (Roles)Model.Role.RoleId;
                        <div class="form-group">
                        <label>Улога (роља): </label>@roleEnum.GetDescription()
                    </div>
                }

                <div class="form-group" data-property-name="file">
                    <label class="" for="file" style="display: block; clear: both;">Профилна слика</label>
                    <img src="@Model.ProfilePictureUrl" style="width: 120px; margin-bottom: 10px;" />
                </div>

            </div>
        </div>
    </div>
</div>

PisCRM/Views/Employees/Edit.cshtml
@model PisCRM.Models.Employees.EditViewModel
@{
    ViewBag.Title = "Уреди вработен";
    ViewBag.TitleDescription = "Промени податоци за вработениот";
}

<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">

            @using (Html.BeginForm("Edit", "Employees", FormMethod.Post, new { role = "form", enctype = "multipart/form-data" }))
            {
                <div class="box-body">
                    @Html.AntiForgeryToken()

                    @Html.CustomValidationMessage("CreateUserErrorResponse")

                    @Html.EditorForModel()

                    <div class="box-footer">
                        <input type="submit" value="Зачувај промени" class="btn btn-primary" />
                    </div>
                </div>
            }
        </div>
    </div>
</div>




PisCRM/Views/Employees/Index.cshtml
@{
    ViewBag.Title = "Вработени";
    ViewBag.TitleDescription = "Прегледај вработени";
}

<div class="row">
    <div class="col-xs-12">
        <div class="box" id="ajax-paging-wrap">
            @Html.Action("IndexPaging")
        </div><!-- /.box -->
    </div>
</div>

@section Scripts
{
    <script type="text/javascript">

        function AjaxPagingCall(page, searchWord) {
            $.ajax({
                url: '@Url.Action("IndexPaging")',
                data: {
                    'page': page, 'searchWord': searchWord
                },
                type: 'GET',
                cache: false,
                success: function (data) {
                    $('#ajax-paging-wrap').html(data);
                }
            });
            return false;
        }
    </script>
}

PisCRM/Views/Employees/IndexPaging.cshtml
@using Roles = PisCRM.Contracts.Enums.Roles;
@model PagedData<ApplicationUser>

@{ Layout = null; }

<div class="box-header">
</div><!-- /.box-header -->
<div class="box-body table-responsive">
    <div id="example1_wrapper" class="dataTables_wrapper form-inline" role="grid">
        <div class="row">
            <div class="col-xs-6">
            </div>
            <div class="col-xs-6">
                <div class="dataTables_filter" id="example1_filter" style="text-align: right;">
                    <input type="text" class="form-control" value="@Model.SearchWord" id="searchWord" placeholder="Барај по име, презиме или email..." style="min-width: 300px;">
                    <span class="input-group-btn" style="display: inline;">
                        <button type="submit" name="search" data-search-btn="true" class="btn btn-info btn-flat">
                            <i class="fa fa-search"></i>
                        </button>
                        @if (!string.IsNullOrEmpty(Model.SearchWord))
                        {
                            <button class="btn btn-warning btn-flat" data-clear-search-btn="true">Избриши барање</button>
                        }
                    </span>
                </div>
            </div>
        </div>
        <table id="example1" class="table table-bordered table-striped dataTable" aria-describedby="example1_info">
            <thead>
                <tr role="row">
                    <th role="columnheader" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Row number: activate to sort column descending">#</th>
                    <th role="columnheader" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Name: activate to sort column ascending">Email</th>
                    <th role="columnheader" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Date Created: activate to sort column ascending">Име и презиме</th>
                    <th role="columnheader" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Date Created: activate to sort column ascending">Работна позиција</th>
                    @if (SiteSession.CurrentUser != null
                            && SiteSession.CurrentUser.Role.RoleId == (int)Roles.Admin)
                    {
                        <th role="columnheader" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Date Created: activate to sort column ascending">Улога (роља)</th>
                    }
                    <th rowspan="1" colspan="1"></th>
                    @if (SiteSession.CurrentUser != null
                            && SiteSession.CurrentUser.Role.RoleId == (int)Roles.Admin)
                    {
                        <th rowspan="1" colspan="1"></th>
                        <th rowspan="1" colspan="1"></th>
                    }
                </tr>
            </thead>

            @{ int nrOfRows = 0; }
            <tbody role="alert" aria-live="polite" aria-relevant="all">
                @foreach (var item in Model.Data)
                {
                    nrOfRows++;
                    int currentNumber = (Model.CurrentPage - 1) * Model.PageSize + nrOfRows;

                    <tr class="@if (currentNumber % 2 != 0) { <text>odd</text> } else { <text>even</text> }">
                        <td class="sorting_1">@currentNumber.ToString()</td>
                        <td class=" ">@item.Email</td>
                        <td class=" ">@item.FullName</td>
                        <td class=" ">@item.WorkPosition</td>
                        @if (SiteSession.CurrentUser != null
                            && SiteSession.CurrentUser.Role.RoleId == (int)Roles.Admin)
                        {
                            var roleEnum = (Roles)item.Role.RoleId;
                            <td class=" ">@roleEnum.GetDescription()</td>
                        }
                        <td class=" ">@Html.ActionLink("Детали", "Details", new { id = item.Id }, new { @class = "btn btn-success" })</td>
                        @if (SiteSession.CurrentUser != null
                            && SiteSession.CurrentUser.Role.RoleId == (int)Roles.Admin)
                        {
                            <td class=" ">@Html.ActionLink("Промени", "Edit", new { id = item.Id }, new { @class = "btn btn-primary" })</td>
                            <td class=" ">@Html.ActionLink("Избриши", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })</td>
                        }
                    </tr>
                }
            </tbody>
        </table>
        @Helpers.Pager(Model.ItemCount, Model.CurrentPage, Model.PageCount, Model.PageSize, "вработени")
    </div>
</div><!-- /.box-body -->