PisCRM/Models/Clients/CreateEditViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace PisCRM.Models.Clients
{
    public class CreateEditViewModel
    {
        [System.Web.Mvc.HiddenInput]
        public int Id { get; set; }

        [Required(ErrorMessage = "Внесете Име и презиме")]
        [StringLength(200, ErrorMessage = "Max. 200 карактери.")]
        [Display(Name = "Име и презиме")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Внесете Email адреса.")]
        [EmailAddress(ErrorMessage = "Внесете валидна Email адреса.")]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Внесете Компанија.")]
        [StringLength(100, ErrorMessage = "Max. 100 карактери.")]
        [Display(Name = "Компанија")]
        public string Company { get; set; }

        [StringLength(1000, ErrorMessage = "Max. 1000 карактери.")]
        [Display(Name = "Проекти")]
        public string Projects { get; set; }
    }
}

PisCRM/Models/Employees/EditViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PisCRM.Models.Employees
{
    public class EditViewModel
    {
        [System.Web.Mvc.HiddenInput]
        public int Id { get; set; }

        //[Required(ErrorMessage = "Внесете Email адреса.")]
        //[EmailAddress(ErrorMessage = "Внесете валидна Email адреса.")]
        //[Display(Name = "Email")]
        //public string Email { get; set; }

        [Required(ErrorMessage = "Внесете Име.")]
        [StringLength(100, ErrorMessage = "Max. 100 карактери.")]
        [Display(Name = "Име")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Внесете Презиме.")]
        [StringLength(100, ErrorMessage = "Max. 100 карактери.")]
        [Display(Name = "Презиме")]
        public string LastName { get; set; }

        [StringLength(100, ErrorMessage = "Max. 100 карактери.")]
        [Display(Name = "Работна позиција")]
        public string WorkPosition { get; set; }

        [Required(ErrorMessage = "Селектирајтe Роља")]
        [Display(Name = "Селектирајтe Роља")]
        public int RoleId { get; set; }

        [Display(Name = "Профилна слика")]
        public string ProfilePictureUrl { get; set; }
    }
}

PisCRM/Controllers/ClientsController.cs
using PisCRM.Framework;
using PisCRM.Infrastructure;
using System;
using System.Linq;
using System.Web.Mvc;
using PisCRM.Infrastructure.Alerts;
using PisCRM.Models.Employees;
using Domain.Managers;
using PisCRM.Contracts;
using Omu.ValueInjecter;
using PisCRM.Models.Clients;

namespace PisCRM.Controllers
{
    [Authorize]
    public class ClientsController : BaseController
    {
        private readonly ClientManager _clientManager;

        public ClientsController(ICurrentUser currentUser, ClientManager clientManager) : base(currentUser)
        {
            _clientManager = clientManager;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult IndexPaging(int page = 1, string searchWord = "")
        {
            var model = new PagedData<Client>();
            IQueryable<Client> users = _clientManager.GetClients(searchWord);
            model.Data = model.PreparePage(users);

            return View(model);
        }

        //[AdminRoleFilter]
        public ActionResult Create()
        {
            var model = new CreateEditViewModel();
            return View(model);
        }

        //[AdminRoleFilter]
        [HttpPost]
        public ActionResult Create(CreateEditViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var client = new Client { DateCreated = DateTime.UtcNow };
            client.InjectFrom(model);

            _clientManager.Insert(client);

            //if (Request.Files.Count == 1)
            //_employeeManager.SaveProfilePhoto(user.Id, Request.Files[0]);

            return RedirectToAction<ClientsController>(c => c.Index())
                .WithSuccess("Клиентот е успешно креиран!");
        }

        public ActionResult Details(int id)
        {
            var model = _clientManager.GetSingle(id);

            if (model == null)
            {
                return RedirectToAction<ClientsController>(c => c.Index())
                    .WithError("Не постои таков клиент.");
            }

            return View(model);
        }

        //[AdminRoleFilter]
        public ActionResult Edit(int id)
        {
            var user = _clientManager.GetSingle(id);

            if (user == null)
            {
                return RedirectToAction<ClientsController>(c => c.Index())
                    .WithError("Не е пронајден клиентот! Обидете се повторно.");
            }

            var model = new EditViewModel();
            model.InjectFrom(user);
            return View(model);
        }

        //[AdminRoleFilter]
        [HttpPost]
        public ActionResult Edit(CreateEditViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var client = _clientManager.GetSingle(model.Id);

            if (client == null)
                return RedirectToAction<ClientsController>(c => c.Index())
                    .WithError("Не е пронајден клиентот! Обидете се повторно.");

            client.Name = model.Name;
            client.Email = model.Email;
            client.Company = model.Company;
            client.Projects = model.Projects;

            //if (Request.Files.Count == 1)
            //    _employeeManager.SaveProfilePhoto(user.Id, Request.Files[0]);

            _clientManager.Update(client);

            return RedirectToAction<ClientsController>(c => c.Index())
                .WithSuccess("Информациите за клиентот се успешно зачувани!");
        }

        //[AdminRoleFilter]
        public ActionResult Delete(int id)
        {
            var model = _clientManager.GetSingle(id);

            if (model == null)
                return RedirectToAction<ClientsController>(c => c.Index())
                    .WithError("Не е пронајден клиентот! Обидете се повторно.");

            return View(model);
        }

        //[AdminRoleFilter]
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            var client = _clientManager.GetSingle(id);

            if (client == null)
                return RedirectToAction<ClientsController>(c => c.Index())
                    .WithError("Не е пронајден клиентот! Обидете се повторно.");

            _clientManager.Delete(client.Id);

            return RedirectToAction<ClientsController>(c => c.Index())
                .WithSuccess("Клиентот е успешно избришан!");
        }
    }
}

PisCRM/Views/Clients/Create.cshtml
@model PisCRM.Models.Clients.CreateEditViewModel
@{
    ViewBag.Title = "Креирај клиент";
    ViewBag.TitleDescription = "Креирај нов клиент";
}

<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">

            @using (Html.BeginForm("Create", "Clients", FormMethod.Post, new { role = "form", enctype = "multipart/form-data" }))
            {
                <div class="box-body">
                    @Html.AntiForgeryToken()

                    @Html.EditorForModel()

                    @*<div class="form-group" data-property-name="file">
                        <label class="" for="file">Профилна слика</label>
                        <input class="upload" type="file" id="file" accept="image/*" name="file" onchange="fileSelected('image', 'file')" />
                    </div>*@

                    <div class="box-footer">
                        <input type="submit" value="Креирај клиент" class="btn btn-primary" />
                    </div>
                </div>
            }
        </div>
    </div>
</div>

PisCRM/Views/Clients/Delete.cshtml
@model Client
@{
    ViewBag.Title = "Избриши клиент";
    ViewBag.TitleDescription = "";
}

<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">

            @using (Html.BeginForm("Delete", "Clients", FormMethod.Post, new { role = "form" }))
            {
                <div class="box-body">
                    @Html.AntiForgeryToken()

                    @Html.HiddenFor(model => model.Id)
                    <p>
                        Дали сте сигурни дека сакате да го избришете клиентот: <b>@Model.Name </b>
                        со Email адреса: <b>@Model.Email</b>?
                    </p>
                    <p>Акцијата е неповратна!</p>

                    <div class="box-footer">
                        <input type="submit" value="Избриши клиент" class="btn btn-danger" />
                    </div>
                </div>
            }
        </div>
    </div>
</div>

PisCRM/Views/Clients/Details.cshtml
@model PisCRM.Contracts.Client

@{ ViewBag.Title = "Детали - " + Model.Name;
 ViewBag.TitleDescription = "";
}

<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">

            <div class="box-body">
                <div class="form-group">
                    <label>Име и презиме: </label>@Model.Name
                </div>

                <div class="form-group">
                    <label>Email адреса: </label>@Model.Email
                </div>

                <div class="form-group">
                    <label>Компанија: </label>@Model.Company
                </div>
                <div class="form-group">
                    <label>Проекти: </label>@Model.Projects
                </div>

                @*<div class="form-group" data-property-name="file">
                    <label class="" for="file" style="display: block; clear: both;">Профилна слика</label>
                    <img src="@Model.ProfilePictureUrl" style="width: 120px; margin-bottom: 10px;" />
                </div>*@

            </div>
        </div>
    </div>
</div>

PisCRM/Views/Clients/Edit.cshtml
@model PisCRM.Models.Clients.CreateEditViewModel
@{
    ViewBag.Title = "Уреди клиент";
    ViewBag.TitleDescription = "Промени податоци за клиентот";
}

<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">

            @using (Html.BeginForm("Edit", "Clients", FormMethod.Post, new { role = "form", enctype = "multipart/form-data" }))
            {
                <div class="box-body">
                    @Html.AntiForgeryToken()

                    @Html.EditorForModel()

                    <div class="box-footer">
                        <input type="submit" value="Зачувај промени" class="btn btn-primary" />
                    </div>
                </div>
            }
        </div>
    </div>
</div>

PisCRM/Views/Clients/Index.cshtml
@{
    ViewBag.Title = "Клиенти";
    ViewBag.TitleDescription = "Прегледај клиенти";
}

<div class="row">
    <div class="col-xs-12">
        <div class="box" id="ajax-paging-wrap">
            @Html.Action("IndexPaging")
        </div><!-- /.box -->
    </div>
</div>

@section Scripts
{
    <script type="text/javascript">

        function AjaxPagingCall(page, searchWord) {
            $.ajax({
                url: '@Url.Action("IndexPaging")',
                data: {
                    'page': page, 'searchWord': searchWord
                },
                type: 'GET',
                cache: false,
                success: function (data) {
                    $('#ajax-paging-wrap').html(data);
                }
            });
            return false;
        }
    </script>
}

PisCRM/Views/Clients/IndexPaging.cshtml
@model PagedData<Client>

@{ Layout = null; }

<div class="box-header">
</div><!-- /.box-header -->
<div class="box-body table-responsive">
    <div id="example1_wrapper" class="dataTables_wrapper form-inline" role="grid">
        <div class="row">
            <div class="col-xs-6">
            </div>
            <div class="col-xs-6">
                <div class="dataTables_filter" id="example1_filter" style="text-align: right;">
                    <input type="text" class="form-control" value="@Model.SearchWord" id="searchWord" placeholder="Барај по име или email..." style="min-width: 300px;">
                    <span class="input-group-btn" style="display: inline;">
                        <button type="submit" name="search" data-search-btn="true" class="btn btn-info btn-flat">
                            <i class="fa fa-search"></i>
                        </button>
                        @if (!string.IsNullOrEmpty(Model.SearchWord))
                        {
                            <button class="btn btn-warning btn-flat" data-clear-search-btn="true">Избриши барање</button>
                        }
                    </span>
                </div>
            </div>
        </div>
        <table id="example1" class="table table-bordered table-striped dataTable" aria-describedby="example1_info">
            <thead>
                <tr role="row">
                    <th role="columnheader" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Row number: activate to sort column descending">#</th>
                    <th role="columnheader" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Name: activate to sort column ascending">Email</th>
                    <th role="columnheader" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Date Created: activate to sort column ascending">Име и презиме</th>
                    <th role="columnheader" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Date Created: activate to sort column ascending">Компанија</th>
                    <th role="columnheader" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Date Created: activate to sort column ascending">Проекти</th>
                    <th rowspan="1" colspan="1"></th>
                    <th rowspan="1" colspan="1"></th>
                    <th rowspan="1" colspan="1"></th>
                </tr>
            </thead>

            @{ int nrOfRows = 0; }
            <tbody role="alert" aria-live="polite" aria-relevant="all">
                @foreach (var item in Model.Data)
                {
                    nrOfRows++;
                    int currentNumber = (Model.CurrentPage - 1) * Model.PageSize + nrOfRows;

                    <tr class="@if (currentNumber % 2 != 0) { <text>odd</text> } else { <text>even</text> }">
                        <td class="sorting_1">@currentNumber.ToString()</td>
                        <td class=" ">@item.Email</td>
                        <td class=" ">@item.Name</td>
                        <td class=" ">@item.Company</td>
                        <td class=" ">@item.Projects</td>
                        <td class=" ">@Html.ActionLink("Детали", "Details", new { id = item.Id }, new { @class = "btn btn-success" })</td>
                        @*@if (SiteSession.CurrentUser != null
                            && SiteSession.CurrentUser.Role.RoleId == (int)Roles.Admin)
                        {*@
                            <td class=" ">@Html.ActionLink("Промени", "Edit", new { id = item.Id }, new { @class = "btn btn-primary" })</td>
                            <td class=" ">@Html.ActionLink("Избриши", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })</td>
                        @*}*@
                    </tr>
                }
            </tbody>
        </table>
        @Helpers.Pager(Model.ItemCount, Model.CurrentPage, Model.PageCount, Model.PageSize, "клиенти")
    </div>
</div><!-- /.box-body -->