PisCRM/Models/Contracts/CreateEditViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace PisCRM.Models.Contracts
{
    public class CreateEditViewModel
    {
        [System.Web.Mvc.HiddenInput]
        public int Id { get; set; }

        [Required(ErrorMessage = "Внесете Име")]
        [StringLength(200, ErrorMessage = "Max. 200 карактери.")]
        [Display(Name = "Име")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Внесете Опис.")]
        [StringLength(1000, ErrorMessage = "Max. 1000 карактери.")]
        [Display(Name = "Опис")]
        public string Description { get; set; }

        [DataType(DataType.DateTime)]
        [Display(Name = "Почетен датум")]
        public DateTime StartDate { get; set; }

        [DataType(DataType.DateTime)]
        [Display(Name = "Краен датум")]
        public DateTime EndDate { get; set; }

        [Required(ErrorMessage = "Селектирајтe Клиент.")]
        [Display(Name = "Селектирајте Клиент")]
        public int ClientId { get; set; }
    }
}

PisCRM/Models/Employees/EditViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PisCRM.Models.Employees
{
    public class EditViewModel
    {
        [System.Web.Mvc.HiddenInput]
        public int Id { get; set; }

        //[Required(ErrorMessage = "Внесете Email адреса.")]
        //[EmailAddress(ErrorMessage = "Внесете валидна Email адреса.")]
        //[Display(Name = "Email")]
        //public string Email { get; set; }

        [Required(ErrorMessage = "Внесете Име.")]
        [StringLength(100, ErrorMessage = "Max. 100 карактери.")]
        [Display(Name = "Име")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Внесете Презиме.")]
        [StringLength(100, ErrorMessage = "Max. 100 карактери.")]
        [Display(Name = "Презиме")]
        public string LastName { get; set; }

        [StringLength(100, ErrorMessage = "Max. 100 карактери.")]
        [Display(Name = "Работна позиција")]
        public string WorkPosition { get; set; }

        [Required(ErrorMessage = "Селектирајтe Роља")]
        [Display(Name = "Селектирајтe Роља")]
        public int RoleId { get; set; }

        [Display(Name = "Профилна слика")]
        public string ProfilePictureUrl { get; set; }
    }
}

PisCRM/Controllers/ContractsController.cs
using PisCRM.Framework;
using PisCRM.Infrastructure;
using System;
using System.Linq;
using System.Web.Mvc;
using PisCRM.Infrastructure.Alerts;
using Domain.Managers;
using PisCRM.Contracts;
using Omu.ValueInjecter;
using PisCRM.Models.Contracts;

namespace PisCRM.Controllers
{
    [Authorize]
    public class ContractsController : BaseController
    {
        private readonly ContractManager _contractManager;

        public ContractsController(ICurrentUser currentUser, ContractManager contractManager)
            : base(currentUser)
        {
            _contractManager = contractManager;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult IndexPaging(int page = 1, string searchWord = "")
        {
            var model = new PagedData<Contract>();
            IQueryable<Contract> users = _contractManager.GetContracts(searchWord);
            model.Data = model.PreparePage(users);

            return View(model);
        }

        //[AdminRoleFilter]
        public ActionResult Create()
        {
            var model = new CreateEditViewModel();
            return View(model);
        }

        //[AdminRoleFilter]
        [HttpPost]
        public ActionResult Create(CreateEditViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var contract = new Contract { DateCreated = DateTime.UtcNow };
            contract.InjectFrom(model);

            _contractManager.Insert(contract);

            return RedirectToAction<ContractsController>(c => c.Index())
                .WithSuccess("Договорот е успешно креиран!");
        }

        public ActionResult Details(int id)
        {
            var model = _contractManager.GetSingle(id);

            if (model == null)
            {
                return RedirectToAction<ContractsController>(c => c.Index())
                    .WithError("Не постои таков договор.");
            }

            return View(model);
        }

        //[AdminRoleFilter]
        public ActionResult Edit(int id)
        {
            var contract = _contractManager.GetSingle(id);

            if (contract == null)
            {
                return RedirectToAction<ContractsController>(c => c.Index())
                    .WithError("Не е пронајден договорот! Обидете се повторно.");
            }

            var model = new CreateEditViewModel();
            model.InjectFrom(contract);
            return View(model);
        }

        //[AdminRoleFilter]
        [HttpPost]
        public ActionResult Edit(CreateEditViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var contract = _contractManager.GetSingle(model.Id);

            if (contract == null)
                return RedirectToAction<ContractsController>(c => c.Index())
                    .WithError("Не е пронајден договорот! Обидете се повторно.");

            contract.InjectFrom(model);

            _contractManager.Update(contract);

            return RedirectToAction<ContractsController>(c => c.Index())
                .WithSuccess("Информациите за договорот се успешно зачувани!");
        }

        //[AdminRoleFilter]
        public ActionResult Delete(int id)
        {
            var model = _contractManager.GetSingle(id);

            if (model == null)
                return RedirectToAction<ContractsController>(c => c.Index())
                    .WithError("Не е пронајден договорoт! Обидете се повторно.");

            return View(model);
        }

        //[AdminRoleFilter]
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            var contract = _contractManager.GetSingle(id);

            if (contract == null)
                return RedirectToAction<ContractsController>(c => c.Index())
                    .WithError("Не е пронајден договорот! Обидете се повторно.");

            _contractManager.Delete(contract.Id);

            return RedirectToAction<ContractsController>(c => c.Index())
                .WithSuccess("Договорот е успешно избришан!");
        }
    }
}

PisCRM/Views/Contracts/Create.cshtml
@model PisCRM.Models.Contracts.CreateEditViewModel
@{
    ViewBag.Title = "Креирај договор";
    ViewBag.TitleDescription = "Креирај нов договор";
}

<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">

            @using (Html.BeginForm("Create", "Contracts", FormMethod.Post, new { role = "form", enctype = "multipart/form-data" }))
            {
                <div class="box-body">
                    @Html.AntiForgeryToken()

                    @Html.EditorForModel()

                    <div class="form-group" data-property-name="file">
                        <label class="" for="file">Прикачи фајлoви:</label>
                        <input class="upload" type="file" id="file" accept="image/*" name="file" onchange="fileSelected('image', 'file')" />
                    </div>

                    <div class="box-footer">
                        <input type="submit" value="Креирај договор" class="btn btn-primary" />
                    </div>
                </div>
            }
        </div>
    </div>
</div>

PisCRM/Views/Contracts/Delete.cshtml
@model Contract
    @{
        ViewBag.Title = "Избриши договор";
        ViewBag.TitleDescription = "";
    }

    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">

                @using (Html.BeginForm("Delete", "Contracts", FormMethod.Post, new { role = "form" }))
            {
                    <div class="box-body">
                        @Html.AntiForgeryToken()

                        @Html.HiddenFor(model => model.Id)
                        <p>
                            Дали сте сигурни дека сакате да го избришете договорот: <b>@Model.Name </b>?
                        </p>
                        <p>Акцијата е неповратна!</p>

                        <div class="box-footer">
                            <input type="submit" value="Избриши договор" class="btn btn-danger" />
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>

PisCRM/Views/Contracts/Details.cshtml
@model Contract

@{ ViewBag.Title = "Детали - " + Model.Name;
    ViewBag.TitleDescription = "";
}

<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">

            <div class="box-body">
                <div class="form-group">
                    <label>Име: </label>@Model.Name
                </div>

                <div class="form-group">
                    <label>Опис: </label>@Model.Description
                </div>

                <div class="form-group">
                    <label>Почетен датум: </label>@Model.StartDate
                </div>
                <div class="form-group">
                    <label>Краен Датум: </label>@Model.EndDate
                </div>
                <div class="form-group">
                    <label>Клиент: </label>@Model.Client.Name
                </div>

            </div>
        </div>
    </div>
</div>

PisCRM/Views/Contracts/Edit.cshtml
@model PisCRM.Models.Contracts.CreateEditViewModel
@{
    ViewBag.Title = "Уреди договор";
    ViewBag.TitleDescription = "Промени податоци за договорот";
}

<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">

            @using (Html.BeginForm("Edit", "Contracts", FormMethod.Post, new { role = "form", enctype = "multipart/form-data" }))
            {
                <div class="box-body">
                    @Html.AntiForgeryToken()

                    @Html.EditorForModel()

                    <div class="form-group" data-property-name="file">
                        <label class="" for="file">Прикачи фајлoви:</label>
                        <input class="upload" type="file" id="file" accept="image/*" name="file" onchange="fileSelected('image', 'file')" />
                    </div>

                    <div class="box-footer">
                        <input type="submit" value="Зачувај промени" class="btn btn-primary" />
                    </div>
                </div>
            }
        </div>
    </div>
</div>

PisCRM/Views/Contracts/Index.cshtml
@{
    ViewBag.Title = "Договори";
    ViewBag.TitleDescription = "Прегледај договори";
}

<div class="row">
    <div class="col-xs-12">
        <div class="box" id="ajax-paging-wrap">
            @Html.Action("IndexPaging")
        </div><!-- /.box -->
    </div>
</div>

@section Scripts
{
    <script type="text/javascript">

        function AjaxPagingCall(page, searchWord) {
            $.ajax({
                url: '@Url.Action("IndexPaging")',
                data: {
                    'page': page, 'searchWord': searchWord
                },
                type: 'GET',
                cache: false,
                success: function (data) {
                    $('#ajax-paging-wrap').html(data);
                }
            });
            return false;
        }
    </script>
}

PisCRM/Views/Contracts/IndexPaging.cshtml
@model PagedData<Contract>

@{ Layout = null; }

<div class="box-header">
</div><!-- /.box-header -->
<div class="box-body table-responsive">
    <div id="example1_wrapper" class="dataTables_wrapper form-inline" role="grid">
        <div class="row">
            <div class="col-xs-6">
            </div>
            <div class="col-xs-6">
                <div class="dataTables_filter" id="example1_filter" style="text-align: right;">
                    <input type="text" class="form-control" value="@Model.SearchWord" id="searchWord" placeholder="Барај по име..." style="min-width: 300px;">
                    <span class="input-group-btn" style="display: inline;">
                        <button type="submit" name="search" data-search-btn="true" class="btn btn-info btn-flat">
                            <i class="fa fa-search"></i>
                        </button>
                        @if (!string.IsNullOrEmpty(Model.SearchWord))
                        {
                            <button class="btn btn-warning btn-flat" data-clear-search-btn="true">Избриши барање</button>
                        }
                    </span>
                </div>
            </div>
        </div>
        <table id="example1" class="table table-bordered table-striped dataTable" aria-describedby="example1_info">
            <thead>
                <tr role="row">
                    <th role="columnheader" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Row number: activate to sort column descending">#</th>
                    <th role="columnheader" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Date Created: activate to sort column ascending">Име</th>
                    <th role="columnheader" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Date Created: activate to sort column ascending">Почетен датум</th>
                    <th role="columnheader" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Date Created: activate to sort column ascending">Краен датум</th>
                    <th role="columnheader" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Date Created: activate to sort column ascending">Клиент</th>
                    <th rowspan="1" colspan="1"></th>
                    <th rowspan="1" colspan="1"></th>
                    <th rowspan="1" colspan="1"></th>
                </tr>
            </thead>

            @{ int nrOfRows = 0; }
            <tbody role="alert" aria-live="polite" aria-relevant="all">
                @foreach (var item in Model.Data)
                {
                    nrOfRows++;
                    int currentNumber = (Model.CurrentPage - 1) * Model.PageSize + nrOfRows;

                    <tr class="@if (currentNumber % 2 != 0) { <text>odd</text> } else { <text>even</text> }">
                        <td class="sorting_1">@currentNumber.ToString()</td>
                        <td class=" ">@item.Name</td>
                        <td class=" ">@item.StartDate</td>
                        <td class=" ">@item.EndDate</td>
                        <td class=" ">@item.Client.Name</td>
                        <td class=" ">@Html.ActionLink("Детали", "Details", new { id = item.Id }, new { @class = "btn btn-success" })</td>
                        @*@if (SiteSession.CurrentUser != null
                            && SiteSession.CurrentUser.Role.RoleId == (int)Roles.Admin)
                        {*@
                            <td class=" ">@Html.ActionLink("Промени", "Edit", new { id = item.Id }, new { @class = "btn btn-primary" })</td>
                            <td class=" ">@Html.ActionLink("Избриши", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })</td>
                        @*}*@
                    </tr>
                }
            </tbody>
        </table>
        @Helpers.Pager(Model.ItemCount, Model.CurrentPage, Model.PageCount, Model.PageSize, "договори")
    </div>
</div><!-- /.box-body -->